name: elma
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.12
  cupertino_icons: ^1.0.6
  sms_otp_auto_verify: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  fan_carousel_image_slider: ^0.1.2
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - images/
